<%--
  Created by IntelliJ IDEA.
  User: jthota
  Date: 1/4/2024
  Time: 3:31 PM
  To change this template use File | Settings | File Templates.
--%>

<%@ page contentType="text/html;charset=UTF-8" language="java" %>

<link href="/platform/css/home.css" rel="stylesheet" type="text/css"/>

<div class="container">
    <div class="about-platform-header" align="center">
        <h2>Somatic Cell Genome Editing (SCGE) Platform</h2>
    </div>
</div>

<div class="container home-container">
    <div class="row">
        <div class="col-md-8">
            <div class="hero-section">
                <div align="center">
                    <div class="hero-image-wrapper">
                        <%--            <img class="img-fluid" src="/platform/images/platform-overview.png" />--%>
                        <img class="img-fluid" src="/platform/common/images/Platform_Home_Page_V2.png" width="100%"/>
                    </div>
                </div>
            </div>

            <div class="about-content-card about-text">
                <div class="text-justify">
                    <p>The National Institutes of Health (NIH) is leading an effort to help accelerate genome editing approaches from the lab to the clinic through the <a href="https://scge.mcw.edu/">Somatic Cell Genome Editing (SCGE) Program</a>.
                        <a href="https://scge.mcw.edu/phase-1-project-goals/">Phase I</a> of the program included the <a href="https://scge.mcw.edu/toolkit" target="_blank">SCGE Toolkit</a> to disseminate the outcomes focused on translating safe and effective genome editing therapeutics into the clinic. During <a href="https://scge.mcw.edu/about-the-scge-phase-2/">Phase 2</a> the <a href="https://scge.mcw.edu/phase-2-tcdc/">Translational Coordination and Dissemination Center (TCDC)</a> will support and work cooperatively with all initiatives, projects, and members to facilitate the objectives of the entire SCGE Consortium and the broader gene editing therapy field through development of the SCGE Platform, consisting of multiple initiatives.
                    </p>
                    <ul>
                        <li>The SCGE Platform is tracking and curating information on current and past gene therapy and gene editing clinical trials to help investigators leverage other successful trials
                            <ul>
                                <li>Explore the <a href="/platform/data/search/ClinicalTrial">Gene Therapy Trial Browser</a></li>
                            </ul>
                        </li>
                        <li>The Platform will help investigators accelerate their efforts to get their therapies to the clinic by:
                            <ul>
                                <li>Collecting and collating useful resources and form templates specific to gene editing therapies and products to help investigators work with and submit Investigational New Drug (IND) applications to the Federal Drug Administration (FDA) </li>
                                <li>Learning and communicating best practices regarding a successful IND application </li>
                                <li>Collecting and sharing data and protocols generated by consortium laboratories</li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>

            <div class="tools-resources-section">
                <h4>SCGE Platform Tools & Resources</h4>
                <div class="row tool-cards-container">
                <div class="col-md-3 col-sm-6">
                    <div class="tool-card">
                        <div class="tool-card-icon">
                            <i class="fas fa-dna"></i>
                        </div>
                        <h3 class="tool-card-title">Gene Therapy Trial Browser</h3>
                        <p class="tool-card-description">
                            Explore our comprehensive database of current and past gene therapy and gene editing clinical trials.
                        </p>
                        <a href="/platform/data/search/ClinicalTrial" class="tool-card-link">Explore Trials</a>
                    </div>
                </div>
                <div class="col-md-3 col-sm-6">
                    <div class="tool-card">
                        <div class="tool-card-icon">
                            <i class="fas fa-file-medical"></i>
                        </div>
                        <h3 class="tool-card-title">SCGE Regulatory Documents</h3>
                        <p class="tool-card-description">
                            Access pre-IND briefing books, FDA responses, and regulatory guidance documents.
                        </p>
                        <a href="/platform/public/documents/regulatory" class="tool-card-link">View Documents</a>
                    </div>
                </div>
                <div class="col-md-3 col-sm-6">
                    <div class="tool-card">
                        <div class="tool-card-icon">
                            <i class="fas fa-file-alt"></i>
                        </div>
                        <h3 class="tool-card-title">Templates & Forms</h3>
                        <p class="tool-card-description">
                            Download IND application templates, forms, and resources to streamline your regulatory submission process.
                        </p>
                        <a href="/platform/data/ind/templates" class="tool-card-link">Access Templates</a>
                    </div>
                </div>
                <div class="col-md-3 col-sm-6">
                    <div class="tool-card">
                        <div class="tool-card-icon">
                            <i class="fas fa-project-diagram"></i>
                        </div>
                        <h3 class="tool-card-title">Projects</h3>
                        <p class="tool-card-description">
                            Explore Phase 2 IND-enabling studies and collaborative research projects in genome editing.
                        </p>
                        <a href="https://scge.mcw.edu/phase-2-ind-enabling-studies/" target="_blank" class="tool-card-link">View Projects</a>
                    </div>
                </div>
                </div>
            </div>

            <div class="sidebar-section">
                <h4>External Resources/Links</h4>
                <ol class="list-unstyled mb-0">
                    <li><a href="https://www.fda.gov/drugs/investigational-new-drug-ind-application/ind-forms-and-instructions" target="_blank">FDA IND Forms and Instructions</a></li>
                    <li><a href="https://www.fda.gov/drugs/types-applications/investigational-new-drug-ind-application#FDA%20Guidances%20for%20Investigational%20New%20Drugs" target="_blank">FDA Guidance Documents for INDs</a></li>
                </ol>
            </div>
        </div><!-- /.col-md-8 -->

        <aside class="col-md-4 blog-sidebar">

            <div class="news-section">
                <h3>Latest News & Updates</h3>

                <div class="news-item">
                    <div class="news-item-date">October 31, 2025</div>
                    <h4 class="news-item-title">
                        <a href="#">SCGE Regulatory Documents – First Set Released</a>
                    </h4>
                    <p class="news-item-excerpt">
                        Full set of pre-IND briefing books and the FDA's written responses of projects "Postnatal and Prenatal Therapeutic Base Editing for Metabolic Diseases" and "Personalized prime editing as a platform for hepatic inborn errors of metabolism" are available on the SCGE Translational Coordination and Dissemination Center
                    </p>
                    <a href="/platform/public/documents/regulatory" class="news-item-link">Explore &rarr;</a>
                </div>
                <div class="news-item">
                    <div class="news-item-date">January 15, 2025</div>
                    <h4 class="news-item-title">
                        <a href="#">New Gene Therapy Trial Browser Launched</a>
                    </h4>
                    <p class="news-item-excerpt">
                        The SCGE Consortium is excited to announce the launch of our comprehensive Gene Therapy Trial Browser,
                        providing researchers and clinicians with access to the latest clinical trial information in genome editing.
                    </p>
                    <a href="/platform/data/search/ClinicalTrial" class="news-item-link">Explore &rarr;</a>
                </div>
            </div>

            <%@include file="bsky_feeds.jsp"%>

            <div class="social-links-wrapper">
                <h4>Follow us on</h4>
                <ul class="list-group list-group-horizontal">
                    <li class="list-group-item"><a href="https://twitter.com/somaticediting" target="_blank" title="twitter"><i class="fa-brands fa-x-twitter"></i></a></li>
                    <li class="list-group-item"><a href="https://www.linkedin.com/company/somatic-cell-genome-editing-consortium/about/" target="_blank" title="LinkedIn"><i class="fab fa-linkedin mr-1"></i></a></li>
                    <li class="list-group-item"><a href="https://www.youtube.com/channel/UCnMSf_YZdv1gIuqPmB6vrYw" target="_blank" title="YouTube"><i class="fab fa-youtube mr-1"></i></a></li>
                    <li class="list-group-item"><a href="https://bsky.app/profile/scge.bsky.social" target="_blank" title="Bluesky"><i class="fab fa-bluesky mr-1"></i></a></li>
                </ul>
            </div>
        </aside><!-- /.blog-sidebar -->

    </div><!-- /.row -->
</div><!-- /.container -->